version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "client/yarn.lock"}}
          - v1-dependencies-{{ arch }}-

      - run:
          name: npm install yarn
          command: |
            YARN_VERSION=1.7.0
            if [[ $(yarn --version) != $YARN_VERSION ]]; then
              sudo npm install -g yarn@$YARN_VERSION;
              sudo chmod a+x /usr/local/bin/yarn
            fi

      - run: yarn install

      - save_cache:
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "client/yarn.lock"}}
          paths:
            - ./node_modules
            - ./client/node_modules

      - run: yarn lint

      - run:
          name: yarn client:test
          command: cd client && yarn test:coverage --ci --color --reporters=default --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT: ../tmp/test-results/jest-client.xml

      - run:
          name: yarn server:test
          command: yarn server:test:coverage --ci --color --reporters=default --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT: ./tmp/test-results/jest-server.xml

      - store_test_results:
          path: ./tmp/test-results
